import { randomUUID } from "node:crypto";
import type { Context } from "cordis";

import { createNodeId } from "../../../brand/ids.js";
import type { NodeId, ProjectId } from "../../../brand/ids.js";
import type { JsonObject, JsonValue } from "../../../llm/types.js";
import { NodeError } from "../../../node/errors.js";
import type { ControlPurpose } from "../../../node/model.js";
import type { CreateNodeInput } from "../../../node/store.js";
import { AgentBindingError, requireMainBinding } from "../../../project/binding.js";
import { RoadmapError } from "../../../roadmap/errors.js";
import type { RoadmapDefinition } from "../../../roadmap/model.js";
import { ToolExecutionError } from "../../errors.js";
import type { ToolDefinition } from "../../types.js";
import {
  agentRoadmapArtifact,
  createAgentRoadmapView,
  formatAgentRoadmapView,
} from "./output.js";

export const WRITE_ROADMAP_TOOL_NAME = "write_roadmap";

const writeRoadmapSchema: JsonObject = {
  type: "object",
  properties: {
    reason: {
      type: "string",
      description: "Why this initial Roadmap is being created.",
    },
    nodes: {
      type: "array",
      description: "Initial Roadmap nodes in the intended presentation order. Dependencies are expressed with proposal-local keys.",
      items: {
        type: "object",
        properties: {
          key: {
            type: "string",
            description: "Proposal-local identifier used only by depends_on references. It is not the persistent Node ID.",
          },
          kind: {
            type: "string",
            enum: ["work", "control"],
          },
          title: {
            type: "string",
          },
          goal: {
            type: "string",
            description: "Work Node goal. Required only for work Nodes.",
          },
          done_when: {
            type: "array",
            description: "Acceptance criteria for a work Node. Required only for work Nodes.",
            items: { type: "string" },
          },
          control: {
            type: "string",
            enum: ["start", "end", "checkpoint"],
            description: "Control purpose. Required only for control Nodes.",
          },
          required: {
            type: "boolean",
          },
          depends_on: {
            type: "array",
            description: "Proposal-local keys of predecessor Nodes.",
            items: { type: "string" },
          },
        },
        required: ["key", "kind", "title", "required", "depends_on"],
        additionalProperties: false,
      },
    },
  },
  required: ["reason", "nodes"],
  additionalProperties: false,
};

interface ProposalNodeBase {
  readonly key: string;
  readonly title: string;
  readonly required: boolean;
  readonly dependsOn: readonly string[];
}

type ProposalNode =
  | (ProposalNodeBase & {
      readonly kind: "work";
      readonly goal: string;
      readonly doneWhen: readonly string[];
    })
  | (ProposalNodeBase & {
      readonly kind: "control";
      readonly control: ControlPurpose;
    });

interface RoadmapProposal {
  readonly reason: string;
  readonly nodes: readonly ProposalNode[];
}

export function createWriteRoadmapTool(ctx: Context): ToolDefinition {
  return {
    name: WRITE_ROADMAP_TOOL_NAME,
    description: "Create the initial Roadmap for the current Project. This is a Main-Agent-only creation boundary; persistent Node IDs are generated by Navo and the operation fails if a Roadmap already exists.",
    parameters: writeRoadmapSchema,
    execute(arguments_, execution) {
      try {
        execution.signal.throwIfAborted();
        const binding = requireMainBinding(ctx, execution.sessionId);
        if (ctx.roadmaps.get(binding.projectId) !== undefined) {
          throw new ToolExecutionError(
            `Project '${binding.projectId}' already owns a Roadmap.`,
            "A Roadmap already exists for this Project. Read it first and use the Roadmap modification capability for later changes.",
          );
        }

        const proposal = parseProposal(arguments_);
        const ids = new Map<string, NodeId>(
          proposal.nodes.map((node) => [node.key, createNodeId(randomUUID())]),
        );
        const newNodes = proposal.nodes.map((node) => ({
          nodeId: ids.get(node.key)!,
          input: toCreateNodeInput(binding.projectId, node),
        }));
        const definition: RoadmapDefinition = {
          projectId: binding.projectId,
          nodes: proposal.nodes.map((node) => ids.get(node.key)!),
          edges: proposal.nodes.flatMap((node) => node.dependsOn.map((dependency) => ({
            from: ids.get(dependency)!,
            to: ids.get(node.key)!,
          }))),
        };

        const snapshot = ctx.roadmaps.create({
          definition,
          reason: proposal.reason,
          newNodes,
        });
        const view = createAgentRoadmapView(snapshot, ctx.nodes.getByProject(binding.projectId));
        return {
          content: `Roadmap created successfully.\n\n${formatAgentRoadmapView(view)}`,
          artifact: agentRoadmapArtifact(view),
        };
      } catch (error: unknown) {
        if (error instanceof ToolExecutionError) throw error;
        if (error instanceof AgentBindingError) {
          throw new ToolExecutionError(
            error.message,
            "write_roadmap is available only to the Main Agent of the current Project.",
            { cause: error },
          );
        }
        if (error instanceof RoadmapError) {
          throw new ToolExecutionError(
            error.message,
            roadmapFailureMessage(error),
            { cause: error },
          );
        }
        if (error instanceof NodeError) {
          throw new ToolExecutionError(
            error.message,
            "The Roadmap was not created because one or more proposed Nodes are invalid for the current Project.",
            { cause: error },
          );
        }
        if (error instanceof Error) {
          throw new ToolExecutionError(
            error.message,
            "The Roadmap could not be created.",
            { cause: error },
          );
        }
        throw new ToolExecutionError(
          "Unknown write_roadmap failure.",
          "The Roadmap could not be created.",
        );
      }
    },
  };
}

function parseProposal(arguments_: JsonObject): RoadmapProposal {
  const reason = nonEmptyString(arguments_.reason, "reason");
  const rawNodes = arguments_.nodes;
  if (!Array.isArray(rawNodes) || rawNodes.length === 0) {
    throw invalidProposal("nodes must contain at least one Node.");
  }
  const nodes = rawNodes.map((value, index) => parseNode(value, index));
  const keys = new Set<string>();
  for (const node of nodes) {
    if (keys.has(node.key)) throw invalidProposal(`node key '${node.key}' is duplicated.`);
    keys.add(node.key);
  }
  for (const node of nodes) {
    for (const dependency of node.dependsOn) {
      if (!keys.has(dependency)) {
        throw invalidProposal(`Node '${node.key}' depends on unknown key '${dependency}'.`);
      }
    }
  }
  return Object.freeze({ reason, nodes: Object.freeze(nodes) });
}

function parseNode(value: JsonValue, index: number): ProposalNode {
  if (!isObject(value)) throw invalidProposal(`nodes[${index}] must be an object.`);
  const prefix = `nodes[${index}]`;
  const key = nonEmptyString(value.key, `${prefix}.key`);
  const title = nonEmptyString(value.title, `${prefix}.title`);
  if (typeof value.required !== "boolean") throw invalidProposal(`${prefix}.required must be a boolean.`);
  const dependsOn = nonEmptyStringArray(value.depends_on, `${prefix}.depends_on`, true);
  if (new Set(dependsOn).size !== dependsOn.length) {
    throw invalidProposal(`${prefix}.depends_on contains duplicate keys.`);
  }
  if (dependsOn.includes(key)) throw invalidProposal(`Node '${key}' cannot depend on itself.`);

  if (value.kind === "work") {
    if (value.control !== undefined) throw invalidProposal(`${prefix}.control is valid only for control Nodes.`);
    const goal = nonEmptyString(value.goal, `${prefix}.goal`);
    const doneWhen = nonEmptyStringArray(value.done_when, `${prefix}.done_when`, false);
    return Object.freeze({
      key,
      kind: "work",
      title,
      goal,
      doneWhen: Object.freeze(doneWhen),
      required: value.required,
      dependsOn: Object.freeze(dependsOn),
    });
  }

  if (value.kind === "control") {
    if (value.goal !== undefined || value.done_when !== undefined) {
      throw invalidProposal(`${prefix}.goal and done_when are valid only for work Nodes.`);
    }
    if (value.control !== "start" && value.control !== "end" && value.control !== "checkpoint") {
      throw invalidProposal(`${prefix}.control must be start, end or checkpoint.`);
    }
    return Object.freeze({
      key,
      kind: "control",
      title,
      control: value.control,
      required: value.required,
      dependsOn: Object.freeze(dependsOn),
    });
  }

  throw invalidProposal(`${prefix}.kind must be work or control.`);
}

function toCreateNodeInput(projectId: ProjectId, node: ProposalNode): CreateNodeInput {
  const requirement = node.required ? "required" : "optional";
  if (node.kind === "control") {
    return {
      projectId,
      requirement,
      kind: "control",
      purpose: node.control,
      title: node.title,
    };
  }
  return {
    projectId,
    requirement,
    objective: {
      title: node.title,
      description: node.goal,
      acceptanceCriteria: node.doneWhen,
    },
  };
}

function nonEmptyString(value: JsonValue | undefined, path: string): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw invalidProposal(`${path} must be a non-empty string.`);
  }
  return value.trim();
}

function nonEmptyStringArray(value: JsonValue | undefined, path: string, allowEmpty: boolean): string[] {
  if (!Array.isArray(value)) throw invalidProposal(`${path} must be an array of strings.`);
  if (!allowEmpty && value.length === 0) throw invalidProposal(`${path} must contain at least one acceptance criterion.`);
  return value.map((item, index) => nonEmptyString(item, `${path}[${index}]`));
}

function isObject(value: JsonValue): value is JsonObject {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function invalidProposal(message: string): ToolExecutionError {
  return new ToolExecutionError(
    `Invalid write_roadmap proposal: ${message}`,
    `The Roadmap proposal is invalid: ${message}`,
  );
}

function roadmapFailureMessage(error: RoadmapError): string {
  switch (error.code) {
    case "already-exists":
      return "A Roadmap already exists for this Project. Read it first and use the Roadmap modification capability for later changes.";
    case "cycle":
      return "The Roadmap was not created because its dependencies contain a cycle.";
    case "duplicate-reference":
      return "The Roadmap was not created because the proposal contains duplicate Nodes or dependency edges.";
    case "invalid-reference":
      return "The Roadmap was not created because a Node or dependency reference is invalid.";
    case "project-unavailable":
      return "The Roadmap can be created only while the current Project is active.";
    default:
      return `The Roadmap proposal was rejected: ${error.message}`;
  }
}

export const WriteRoadmapTool = Object.assign(
  function registerWriteRoadmapTool(ctx: Context): () => void {
    const dispose = ctx.effect(() => ctx.tools.register(createWriteRoadmapTool(ctx)), "roadmap.write-roadmap-tool");
    return () => { void dispose(); };
  },
  { inject: ["tools", "projects", "nodes", "roadmaps"] },
);
